### ISSUE TITLE
[Tencent:PMKS] When calling GetCluster after RemoveNodeGroup(), "runtime error: index out of range [0] with length 0" 

### ISSUE THREAD

**Issue by sykim-etri** [cloud-barista/cb-spider#1012]
**What happened**
: Tencent CSP의 ap-seoul, ap-beijing 리전을 대상으로 각각 클러스터 생성 후 add nodegroup 진행(그룹 생성되나 노드 생성에 이슈 있음)하고, remove nodegroup 진행하고 get cluster 진행시 아래와 같은 에러가 발생하였습니다.
상세한 로그는 [error-on-get-cluster-after-remove-nodegroup.txt](https://github.com/cloud-barista/cb-spider/files/13937128/error-on-get-cluster-after-remove-nodegroup.txt)을 참고하시기 바랍니다.

```
[CB-SPIDER].[ERROR]: 2024-01-15 09:02:33 ClusterHandler.go:591, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo.func1() - Failed to Process getNodeGroupInfo() : runtime error: index out of range [0] with length 0

goroutine 6232 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo.func1()
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:590 +0x45
panic({0x4b68680?, 0xc000c15aa0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc}, {0xc001a5d680, 0xb})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:653 +0x11a5
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:470 +0xffb
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster(_, {{_, _}, {_, _}})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:129 +0x1f1
github.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCluster({0xc000c14d68, 0x12}, {0x506bcd9, 0x7}, {0xc00162f4b4, 0x9})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:785 +0xa59
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.GetCluster({0x595da30, 0xc0007aa000})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:413 +0x1a6
github.com/labstack/echo/v4.(*Echo).add.func1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0006d2000, {0x58c3f38?, 0xc00162db20}, 0xc000388500)
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399
net/http.serverHandler.ServeHTTP({0x58b4c90?}, {0x58c3f38?, 0xc00162db20?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001e08510, {0x58d24d8, 0xc001712630})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 336
        /usr/local/go/src/net/http/server.go:3086 +0x5cb

[CB-SPIDER].[ERROR]: 2024-01-15 09:02:33 ClusterHandler.go:473, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterInfo() - Failed to Get Node Group Info :  Failed to Process getNodeGroupInfo() : runtime error: index out of range [0] with length 0

goroutine 6232 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo.func1()
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:590 +0x45
panic({0x4b68680?, 0xc000c15aa0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc}, {0xc001a5d680, 0xb})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:653 +0x11a5
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:470 +0xffb
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster(_, {{_, _}, {_, _}})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:129 +0x1f1
github.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCluster({0xc000c14d68, 0x12}, {0x506bcd9, 0x7}, {0xc00162f4b4, 0x9})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:785 +0xa59
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.GetCluster({0x595da30, 0xc0007aa000})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:413 +0x1a6
github.com/labstack/echo/v4.(*Echo).add.func1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0006d2000, {0x58c3f38?, 0xc00162db20}, 0xc000388500)
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399
net/http.serverHandler.ServeHTTP({0x58b4c90?}, {0x58c3f38?, 0xc00162db20?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001e08510, {0x58d24d8, 0xc001712630})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 336
        /usr/local/go/src/net/http/server.go:3086 +0x5cb

[CB-SPIDER].[ERROR]: 2024-01-15 09:02:33 ClusterHandler.go:133, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster() - Failed to Get ClusterInfo :  Failed to Get Node Group Info :  Failed to Process getNodeGroupInfo() : runtime error: index out of range [0] with length 0

goroutine 6232 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo.func1()
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:590 +0x45
panic({0x4b68680?, 0xc000c15aa0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc}, {0xc001a5d680, 0xb})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:653 +0x11a5
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:470 +0xffb
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster(_, {{_, _}, {_, _}})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:129 +0x1f1
github.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCluster({0xc000c14d68, 0x12}, {0x506bcd9, 0x7}, {0xc00162f4b4, 0x9})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:785 +0xa59
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.GetCluster({0x595da30, 0xc0007aa000})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:413 +0x1a6
github.com/labstack/echo/v4.(*Echo).add.func1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0006d2000, {0x58c3f38?, 0xc00162db20}, 0xc000388500)
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399
net/http.serverHandler.ServeHTTP({0x58b4c90?}, {0x58c3f38?, 0xc00162db20?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001e08510, {0x58d24d8, 0xc001712630})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 336
        /usr/local/go/src/net/http/server.go:3086 +0x5cb

[HISCALL].[211.175.140.148] 2024-01-15 09:02:33 (Monday) github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster():135 - "CloudOS" : "TENCENT", "RegionZone" : "ap-beijing", "ResourceType" : "CLUSTER", "ResourceName" : "ns01_tb12_cmieuh23egvafd7cgn5g", "CloudOSAPI" : "GetCluster()", "ElapsedTime" : "16.5199", "ErrorMSG" : "Failed to Get ClusterInfo :  Failed to Get Node Group Info :  Failed to Process getNodeGroupInfo() : runtime error: index out of range [0] with length 0

goroutine 6232 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo.func1()
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:590 +0x45
panic({0x4b68680?, 0xc000c15aa0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc}, {0xc001a5d680, 0xb})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:653 +0x11a5
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:470 +0xffb
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster(_, {{_, _}, {_, _}})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:129 +0x1f1
github.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCluster({0xc000c14d68, 0x12}, {0x506bcd9, 0x7}, {0xc00162f4b4, 0x9})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:785 +0xa59
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.GetCluster({0x595da30, 0xc0007aa000})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:413 +0x1a6
github.com/labstack/echo/v4.(*Echo).add.func1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0006d2000, {0x58c3f38?, 0xc00162db20}, 0xc000388500)
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399
net/http.serverHandler.ServeHTTP({0x58b4c90?}, {0x58c3f38?, 0xc00162db20?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001e08510, {0x58d24d8, 0xc001712630})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 336
        /usr/local/go/src/net/http/server.go:3086 +0x5cb
"
[CB-SPIDER].[ERROR]: 2024-01-15 09:02:33 ClusterManager.go:787, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCluster() - Failed to Get ClusterInfo :  Failed to Get Node Group Info :  Failed to Process getNodeGroupInfo() : runtime error: index out of range [0] with length 0

goroutine 6232 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo.func1()
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:590 +0x45
panic({0x4b68680?, 0xc000c15aa0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc}, {0xc001a5d680, 0xb})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:653 +0x11a5
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:470 +0xffb
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster(_, {{_, _}, {_, _}})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:129 +0x1f1
github.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCluster({0xc000c14d68, 0x12}, {0x506bcd9, 0x7}, {0xc00162f4b4, 0x9})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:785 +0xa59
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.GetCluster({0x595da30, 0xc0007aa000})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:413 +0x1a6
github.com/labstack/echo/v4.(*Echo).add.func1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da30, 0xc0007aa000})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0006d2000, {0x58c3f38?, 0xc00162db20}, 0xc000388500)
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399
net/http.serverHandler.ServeHTTP({0x58b4c90?}, {0x58c3f38?, 0xc00162db20?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001e08510, {0x58d24d8, 0xc001712630})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 336
        /usr/local/go/src/net/http/server.go:3086 +0x5cb

Path: /spider/cluster/ns01-tb12

================================================
Request Body:
{
  "NameSpace": "",
  "ConnectionName": "tencent-ap-beijing"
}
------------------------------------------------
Response Body:
{
  "message": "Failed to Get ClusterInfo :  Failed to Get Node Group Info :  Failed to Process getNodeGroupInfo() : runtime error: index out of range [0] with length 0\n\ngoroutine 6232 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo.func1()\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:590 +0x45\npanic({0x4b68680?, 0xc000c15aa0?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\ngithub.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getNodeGroupInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc}, {0xc001a5d680, 0xb})\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:653 +0x11a5\ngithub.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.getClusterInfo({0xc00162f5c0, 0x24}, {0xc001633ee0, 0x20}, {0xc00161ede6, 0xa}, {0xc00161f6b0, 0xc})\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:470 +0xffb\ngithub.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources.(*TencentClusterHandler).GetCluster(_, {{_, _}, {_, _}})\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/tencent/resources/ClusterHandler.go:129 +0x1f1\ngithub.com/cloud-barista/cb-spider/api-runtime/common-runtime.GetCluster({0xc000c14d68, 0x12}, {0x506bcd9, 0x7}, {0xc00162f4b4, 0x9})\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:785 +0xa59\ngithub.com/cloud-barista/cb-spider/api-runtime/rest-runtime.GetCluster({0x595da30, 0xc0007aa000})\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:413 +0x1a6\ngithub.com/labstack/echo/v4.(*Echo).add.func1({0x595da30, 0xc0007aa000})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b\ngithub.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da30, 0xc0007aa000})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2\ngithub.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da30, 0xc0007aa000})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef\ngithub.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da30, 0xc0007aa000})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da30, 0xc0007aa000})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc0006d2000, {0x58c3f38?, 0xc00162db20}, 0xc000388500)\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399\nnet/http.serverHandler.ServeHTTP({0x58b4c90?}, {0x58c3f38?, 0xc00162db20?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:2938 +0x8e\nnet/http.(*conn).serve(0xc001e08510, {0x58d24d8, 0xc001712630})\n\t/usr/local/go/src/net/http/server.go:2009 +0x5f4\ncreated by net/http.(*Server).Serve in goroutine 336\n\t/usr/local/go/src/net/http/server.go:3086 +0x5cb\n"
}
```

**What you expected to happen**
: 오류 발생하지 않도록 조치가 필요합니다.

**How to reproduce it (as minimally and precisely as possible)**
: 일회성이긴 해서 조금 더 검토가 필요합니다.

**Anything else we need to know?**
: 

**Environment**
- Source version or branch: 493cb4 after v0.8.1
- OS: 
- Others: 

**Proposed solution**
: 

**Any other context**
:

**Comment by powerkimhub** [comment]
- 추측건데, NodeGroup 삭제가 비동기 호출이기 때문에(PMKS 생성/삭제 API는 비동기 호출) 
  - NodeGroup 삭제 API 호출 반환 이후에도 관련 NodeGroup 내부 자원들이 하나씩 삭제 되는 중일 수 있으며,
  - 이때, GetCluster() 요청 호출로 Cluster 정보를 수집하는 중간에 삭제된 자원의 정보 객체 접근이 발생하는 걸로 생각됩니다.
- 아마도, 오류 발생 시에 시간이 좀 흐른 뒤에 GetCluster() 호출 해보면 정상적일 수도 있겠습니다. 

<br>

- Driver GetCluster() 내부에서 ClustetInfo를 구성하는 정보 수집 시에 Cluster 관련 정보 및 NodeGroup 관련 정보 등을 접근하기 전에 
  - 대상 객체 존재 여부 및 len(slice) 확인 후 접근할 수 있도록 몇 군데 보완이 필요할 것 같습니다. 

- 관련하여, 드라이버 측에서 점검 및 보완 부탁 드립니다.

**Comment by sykim-etri** [comment]
재현이 쉽지 않아 해당 이슈의 해결 여부는 불확실한 상황이지만 CB-TB에 포함된 테스트 스크립트에서 자주 호출되므로 추후 재현되면 다시 검토할 예정입니다.
