### ISSUE TITLE
[Improv. req.] 존재하지 않는 SG 조회 시 에러 메시지 개선

### ISSUE THREAD

**Issue by jihoon-seo** [cloud-barista/cb-spider#185]
(대조군)

- 존재하지 않는 VPC 조회 시

[Request]
`curl -sX GET http://localhost:1024/spider/vpc/VPC-01 -H 'Content-Type: application/json' -d '{ "ConnectionName": "'${CONN_CONFIG}'"}' | json_pp`

[Response]
```JSON
{
   "message" : "[aws-us-east-1-config:vpc:VPC-01] does not exist!"
}
```

---

- 존재하지 않는 SG 조회 시

[Request]
`curl -sX GET http://localhost:1024/spider/securitygroup/SG-01 -H 'Content-Type: application/json' -d '{ "ConnectionName": "'${CONN_CONFIG}'"}' | json_pp`

[Response]
```JSON
{
   "message" : "Internal Server Error"
}
```

[Console log]
```
[CLOUD-BARISTA].[INFO]: 2020-05-07 07:58:33 SecurityHandler.go:311, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/aws/resources.(*AwsSecurityHandler).GetSecurity() - err : <nil>
{"time":"2020-05-07T07:58:33.275060333+09:00","level":"-","prefix":"echo","file":"recover.go","line":"73","message":"[PANIC RECOVER] runtime error: index out of range goroutine 637 [running]:\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1.1(0x109d380, 0x1000, 0xc000580000, 0x11b0080, 0xc0005845a0)\n\t/root/go/src/github.com/labstack/echo/middleware/recover.go:71 +0xf1\npanic(0xf7ada0, 0x1934020)\n\t/usr/local/go/src/runtime/panic.go:522 +0x1b5\nmain.getSecurity(0x11b0080, 0xc0005845a0, 0x0, 0x0)\n\t/root/cb-spider/api-runtime/rest-runtime/CCMRest.go:1078 +0xe0b\ngithub.com/labstack/echo.(*Echo).add.func1(0x11b0080, 0xc0005845a0, 0x109d380, 0x1000)\n\t/root/go/src/github.com/labstack/echo/echo.go:512 +0x87\ngithub.com/labstack/echo/middleware.RecoverWithConfig.func1.1(0x11b0080, 0xc0005845a0, 0x0, 0x0)\n\t/root/go/src/github.com/labstack/echo/middleware/recover.go:78 +0xd5\ngithub.com/labstack/echo/middleware.LoggerWithConfig.func2.1(0x11b0080, 0xc0005845a0, 0x1076ebc, 0x1b)\n\t/root/go/src/github.com/labstack/echo/middleware/logger.go:117 +0x1c0\ngithub.com/labstack/echo/middleware.CORSWithConfig.func1.1(0x11b0080, 0xc0005845a0, 0x3, 0x4)\n\t/root/go/src/github.com/labstack/echo/middleware/cors.go:121 +0x478\ngithub.com/labstack/echo.(*Echo).ServeHTTP(0xc0001901e0, 0x1198d80, 0xc0004fe9a0, 0xc0002c6300)\n\t/root/go/src/github.com/labstack/echo/echo.go:623 +0x16e\nnet/http.serverHandler.ServeHTTP(0xc00017cea0, 0x1198d80, 0xc0004fe9a0, 0xc0002c6300)\n\t/usr/local/go/src/net/http/server.go:2774 +0xa8\nnet/http.(*conn).serve(0xc0005843c0, 0x119b180, 0xc0000ba940)\n\t/usr/local/go/src/net/http/server.go:1878 +0x851\ncreated by net/http.(*Server).Serve\n\t/usr/local/go/src/net/http/server.go:2884 +0x2f4\n\ngoroutine 1 [IO wait]:\ninternal/poll.runtime_pollWait(0x7f7b843e0d08, 0x72, 0x0)\n\t/usr/local/go/src/runtime/netpoll.go:182 +0x56\ninternal/poll.(*pollDesc).wait(0xc0000ed198, 0x72, 0x0, 0x0, 0x1068825)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:87 +0x9b\ninternal/poll.(*pollDesc).waitRead(...)\n\t/usr/local/go/src/internal/poll/fd_poll_runtime.go:92\ninternal/poll.(*FD).Accept(0xc0000ed180, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)\n\t/usr/local/go/src/internal/poll/fd_unix.go:384 +0x1ba\nnet.(*netFD).accept(0xc0000ed180, 0xb4, 0x0, 0x0)\n\t/usr/local/go/src/net/fd_unix.go:238 +0x42\nnet.(*TCPListener).accept(0xc0000b6ab0, 0x3, 0xc000046570, 0xc000046500)\n\t/usr/local/go/src/net/tcpsock_posix.go:139 +0x32\nnet.(*TCPListener).AcceptTCP(0xc0000b6ab0, 0x109f688, 0xc0001574d0, 0x6f6067dd)\n\t/usr/local/go/src/net/tcpsock.go:247 +0x48\ngithub.com/labstack/echo.tcpKeepAliveListener.Accept(0xc0000b6ab0, 0xc0001574f8, 0x7e2476, 0x5eb34119, 0x76adbf)\n\t/root/go/src/github.com/labstack/echo/echo.go:859 +0x2f\nnet/http.(*Server).Serve(0xc00017cea0, 0x1195500, 0xc0000b6ab8, 0x0, 0x0)\n\t/usr/local/go/src/net/http/server.go:2859 +0x22d\ngithub.com/labstack/echo.(*Echo).StartServer(0xc0001901e0, 0xc00017cea0, 0x0, 0x1065f04)\n\t/root/go/src/github.com/labstack/echo/echo.go:714 +0x388\ngithub.com/labstack/echo.(*Echo).Start(...)\n\t/root/go/src/github.com/labstack/echo/echo.go:634\nmain.ApiServer(0xc000157880, 0x2d, 0x2d, 0x10665e9, 0x5)\n\t/root/cb-spider/api-runtime/rest-runtime/CBSpiderRuntime.go:171 +0x54a\nmain.main()\n\t/root/cb-spider/api-runtime/rest-runtime/CBSpiderRuntime.go:139 +0x3dc\n\ngoroutine 19 [chan receive, 698 minutes]:\ngopkg.in/natefinch/lumberjack%2ev2.(*Logger).millRun(0xc0000b8420)\n\t/root/go/src/gopkg.in/natefinch/lumberjack.v2/lumberjack.go:379 +0x58\ncreated by gopkg.in/natefinch/lumberjack%2ev2.(*Logger).mill.func1\n\t/root/go/src/gopkg.in/natefinch/lumberjack.v2/lumberjack.go:390 +0x79\n\ngoroutine 21 [select, 3 minutes]:\ngo.etcd.io/etcd/vendor/google.golang.org/grpc.(*ccBalancerWrapper).watcher(0xc0000baec0)\n\t/root/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:69 +0xc1\ncreated by go.etcd.io/etcd/vendor/google.golang.org/grpc.newCCBalancerWrapper\n\t/root/go/src/go.etcd.io/etcd/vendor/google.golang.org/grpc/balancer_conn_wrappers.go:60 +0x16f\n\ngoroutine 22 [IO wait, 3 minutes]:\ninternal/poll.runtime_pollWait(0x7f7b843e0c38, 0x77, 0xc00008ac00)\n\t/usr/local/go/src/runtime/netpoll.go:182 +0x56\ninternal/poll.(*pollDesc).wait(0xc0000ec918, 0x77, 0x119b200, 0xc0000b8240, 0xc0000ec900)\n\t/usr/local/go/src/in\n"}
{"time":"2020-05-07T07:58:33.275186782+09:00","id":"","remote_ip":"127.0.0.1","host":"localhost:1024","method":"GET","uri":"/spider/securitygroup/SG-01","user_agent":"curl/7.58.0","status":500,"error":"","latency":253978891,"latency_human":"253.978891ms","bytes_in":43,"bytes_out":36}
```

**Comment by powerkimhub** [comment]
😂 @jihoon-seo Thanks.

**Comment by powerkimhub** [comment]
fixed!

ref) https://github.com/cloud-barista/cb-spider/commit/54e950f3119f15782a4bb0117e3636e0ec3431ba
