### ISSUE TITLE
[Ambiguous] print direct msg when starting with $XXX_ROOT not set

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#244]
- 실수로 환경변수 설정 없이 실행할 경우, 
- 모호한 메시지 보단 직접적인 오류 메시지 제공 필요.

**Current MSG**
```
[CLOUD-BARISTA].[ERROR]: 2020-06-23 21:28:53 config.go:63, github.com/cloud-barista/cb-store/config.GetConfigInfos() - open /conf/store_conf.yaml: no such file or directory
panic: open /conf/store_conf.yaml: no such file or directory

goroutine 1 [running]:
github.com/cloud-barista/cb-store/config.GetConfigInfos(0x7fa150e04008)
        /root/go/src/github.com/cloud-barista/cb-store/config/config.go:64 +0x2f3
github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.initialize()
        /root/go/src/github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver/nutsdb-driver.go:31 +0x34
github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver.init.0()
        /root/go/src/github.com/cloud-barista/cb-store/store-drivers/nutsdb-driver/nutsdb-driver.go:27 +0x20
exit status 2

```

**Comment by powerkimhub** [comment]
completed.
cf) https://github.com/cloud-barista/cb-spider/commit/2d36cc9a08d7c6e13e456bc1a89d51670aa5f4ee
