### ISSUE TITLE
[NHN:PMKS] Is it possible to create a cluster with two NodeGroups?

### ISSUE THREAD

**Issue by powerkimhub** [cloud-barista/cb-spider#867]
- Cluster를 생성할 때 NodeGroup을 한개 이상 설정할 수 있는지 확인이 필요합니다.

**Comment by sykim-etri** [comment]
클러스터 생성시 생성할 노드그룹 정보를 입력하지 않으면 runtime error가 발생하고 있습니다.
CB-Spider v0.8.1

```
[CB-SPIDER].[INFO]: 2024-01-31 05:43:54 ClusterHandler.go:36, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.(*NhnCloudClusterHandler).CreateCluster() - NHN Cloud Driver: called CreateCluster()
[CB-SPIDER].[INFO]: 2024-01-31 05:43:54 CommonNhnCloudFunc.go:63, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.GetCallLogScheme() - Call NHNCLOUD CreateCluster()
[CB-SPIDER].[ERROR]: 2024-01-31 05:43:54 ClusterHandler.go:654, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.getClusterInfoRequestJSONString.func1() - Failed to Process getClusterInfoRequestJSONString() : runtime error: index out of range [0] with length 0

goroutine 22922 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.getClusterInfoRequestJSONString.func1()
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:653 +0x45
panic({0x4b68680?, 0xc0014131d0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.getClusterInfoRequestJSONString({{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, {{{0xc0016022d0, 0x1e}, {0xc001b72120, 0x24}}, ...}, ...}, ...)
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:660 +0x699
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.(*NhnCloudClusterHandler).CreateCluster(_, {{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, {{{0xc0016022d0, 0x1e}, {0xc001b72120, ...}}, ...}, ...})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:41 +0x165
github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateCluster({_, _}, {_, _}, {{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, ...})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:479 +0x199d
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.CreateCluster({0x595da50, 0xc00088c0a0})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:171 +0x7ca
github.com/labstack/echo/v4.(*Echo).add.func1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000461680, {0x58c3f58?, 0xc0009c2000}, 0xc000692000)
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399
net/http.serverHandler.ServeHTTP({0x58b4cb0?}, {0x58c3f58?, 0xc0009c2000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001cc6000, {0x58d24f8, 0xc0015b16e0})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 303
        /usr/local/go/src/net/http/server.go:3086 +0x5cb

[CB-SPIDER].[ERROR]: 2024-01-31 05:43:54 ClusterHandler.go:44, github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.(*NhnCloudClusterHandler).CreateCluster() - Failed to Get ClusterInfo JSON String :  Failed to Process getClusterInfoRequestJSONString() : runtime error: index out of range [0] with length 0

goroutine 22922 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.getClusterInfoRequestJSONString.func1()
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:653 +0x45
panic({0x4b68680?, 0xc0014131d0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.getClusterInfoRequestJSONString({{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, {{{0xc0016022d0, 0x1e}, {0xc001b72120, 0x24}}, ...}, ...}, ...)
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:660 +0x699
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.(*NhnCloudClusterHandler).CreateCluster(_, {{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, {{{0xc0016022d0, 0x1e}, {0xc001b72120, ...}}, ...}, ...})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:41 +0x165
github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateCluster({_, _}, {_, _}, {{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, ...})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:479 +0x199d
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.CreateCluster({0x595da50, 0xc00088c0a0})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:171 +0x7ca
github.com/labstack/echo/v4.(*Echo).add.func1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000461680, {0x58c3f58?, 0xc0009c2000}, 0xc000692000)
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399
net/http.serverHandler.ServeHTTP({0x58b4cb0?}, {0x58c3f58?, 0xc0009c2000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001cc6000, {0x58d24f8, 0xc0015b16e0})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 303
        /usr/local/go/src/net/http/server.go:3086 +0x5cb

[CB-SPIDER].[ERROR]: 2024-01-31 05:43:54 ClusterManager.go:481, github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateCluster() - Failed to Get ClusterInfo JSON String :  Failed to Process getClusterInfoRequestJSONString() : runtime error: index out of range [0] with length 0

goroutine 22922 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.getClusterInfoRequestJSONString.func1()
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:653 +0x45
panic({0x4b68680?, 0xc0014131d0?})
        /usr/local/go/src/runtime/panic.go:914 +0x21f
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.getClusterInfoRequestJSONString({{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, {{{0xc0016022d0, 0x1e}, {0xc001b72120, 0x24}}, ...}, ...}, ...)
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:660 +0x699
github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.(*NhnCloudClusterHandler).CreateCluster(_, {{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, {{{0xc0016022d0, 0x1e}, {0xc001b72120, ...}}, ...}, ...})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:41 +0x165
github.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateCluster({_, _}, {_, _}, {{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, ...})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:479 +0x199d
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.CreateCluster({0x595da50, 0xc00088c0a0})
        /home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:171 +0x7ca
github.com/labstack/echo/v4.(*Echo).add.func1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2
github.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef
github.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5
github.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da50, 0xc00088c0a0})
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463
github.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000461680, {0x58c3f58?, 0xc0009c2000}, 0xc000692000)
        /home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399
net/http.serverHandler.ServeHTTP({0x58b4cb0?}, {0x58c3f58?, 0xc0009c2000?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e
net/http.(*conn).serve(0xc001cc6000, {0x58d24f8, 0xc0015b16e0})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4
created by net/http.(*Server).Serve in goroutine 303
        /usr/local/go/src/net/http/server.go:3086 +0x5cb

Path: /spider/cluster

================================================
Request Body:
{
  "NameSpace": "",
  "ConnectionName": "nhncloud-kr-pangyo1",
  "ReqInfo": {
    "Name": "ns01-tb111",
    "Version": "1.24.3",
    "VPCName": "ns01-nhncloud-kr-pangyo1-tb",
    "SubnetNames": [
      "nhncloud-kr-pangyo1-tb"
    ],
    "SecurityGroupNames": [
      "ns01-nhncloud-kr-pangyo1-tb"
    ],
    "NodeGroupList": null
  }
}
------------------------------------------------
Response Body:
{
  "message": "Failed to Get ClusterInfo JSON String :  Failed to Process getClusterInfoRequestJSONString() : runtime error: index out of range [0] with length 0\n\ngoroutine 22922 [running]:\nruntime/debug.Stack()\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x5e\ngithub.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.getClusterInfoRequestJSONString.func1()\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:653 +0x45\npanic({0x4b68680?, 0xc0014131d0?})\n\t/usr/local/go/src/runtime/panic.go:914 +0x21f\ngithub.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.getClusterInfoRequestJSONString({{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, {{{0xc0016022d0, 0x1e}, {0xc001b72120, 0x24}}, ...}, ...}, ...)\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:660 +0x699\ngithub.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources.(*NhnCloudClusterHandler).CreateCluster(_, {{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, {{{0xc0016022d0, 0x1e}, {0xc001b72120, ...}}, ...}, ...})\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/cloud-control-manager/cloud-driver/drivers/nhncloud/resources/ClusterHandler.go:41 +0x165\ngithub.com/cloud-barista/cb-spider/api-runtime/common-runtime.CreateCluster({_, _}, {_, _}, {{{0xc0007de4b0, 0xa}, {0x0, 0x0}}, {0xc0007de498, 0x6}, ...})\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/common-runtime/ClusterManager.go:479 +0x199d\ngithub.com/cloud-barista/cb-spider/api-runtime/rest-runtime.CreateCluster({0x595da50, 0xc00088c0a0})\n\t/home/sykim/go/src/github.com/cloud-barista/cb-spider/api-runtime/rest-runtime/ClusterRest.go:171 +0x7ca\ngithub.com/labstack/echo/v4.(*Echo).add.func1({0x595da50, 0xc00088c0a0})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:536 +0x4b\ngithub.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.BodyDump.BodyDumpWithConfig.func4.1({0x595da50, 0xc00088c0a0})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/body_dump.go:81 +0x2e2\ngithub.com/cloud-barista/cb-spider/api-runtime/rest-runtime.ApiServer.Recover.RecoverWithConfig.func3.1({0x595da50, 0xc00088c0a0})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/recover.go:119 +0xef\ngithub.com/labstack/echo/v4/middleware.LoggerWithConfig.func2.1({0x595da50, 0xc00088c0a0})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/logger.go:119 +0xd5\ngithub.com/labstack/echo/v4/middleware.CORSWithConfig.func1.1({0x595da50, 0xc00088c0a0})\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/middleware/cors.go:142 +0x463\ngithub.com/labstack/echo/v4.(*Echo).ServeHTTP(0xc000461680, {0x58c3f58?, 0xc0009c2000}, 0xc000692000)\n\t/home/sykim/go/pkg/mod/github.com/labstack/echo/v4@v4.9.0/echo.go:646 +0x399\nnet/http.serverHandler.ServeHTTP({0x58b4cb0?}, {0x58c3f58?, 0xc0009c2000?}, 0x6?)\n\t/usr/local/go/src/net/http/server.go:2938 +0x8e\nnet/http.(*conn).serve(0xc001cc6000, {0x58d24f8, 0xc0015b16e0})\n\t/usr/local/go/src/net/http/server.go:2009 +0x5f4\ncreated by net/http.(*Server).Serve in goroutine 303\n\t/usr/local/go/src/net/http/server.go:3086 +0x5cb\n"
}

================================================
```

**Comment by sykim-etri** [comment]
NHN Cloud는 클러스터 생성시 하나의 노드그룹 생성만 지원하고 있습니다.

https://docs.nhncloud.com/ko/Container/NKS/ko/public-api/#_15

**Comment by powerkimhub** [comment]
* Cluster 생성 시 NodeGroup 1개 추가 필요
  * 첫번째 NodeGroup 이름은 `default-worker`로 단일/고정
* Cluster 생성 이후 NodeGroup 추가는 가능
